### ISSUE TITLE
2 bytes will be lost

### ISSUE THREAD

**Issue by wuruifeng8888** [mikerabat/FastBase64#1]
If a jpg file or compressed file is encoded with Fastbase64 and then decoded and saved to a jpg file or compressed file, 2 bytes will be lost （test with delphi 11.3）

**Comment by mikerabat** [comment]
Hi. Thanks for pointing that out. Can you provide me a small example that shows the problem. I actually found that the memory allocation in the decoding routine allocated too much memory - it took the padding not into account. So the last 1 or 2 bytes
could be 0.

**Comment by mikerabat** [comment]
Please check - should be fixed now. I took too less care of allocating the buffers (too much as far as I can see...) which resulted in size mishap. I created a small unit test project that checks now for that...
